version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/adlermore.ru:/etc/nginx/ssl
      - /etc/letsencrypt/live/adlermore.ru:/etc/nginx/ssl-links:ro
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
