version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/conf.d/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
