version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/adlermore.ru:/etc/nginx/ssl
      - /etc/letsencrypt/live/adlermore.ru:/etc/nginx/ssl-links:ro
    restart: unless-stopped
